### ISSUE TITLE
msg.text has problem with Persian

### ISSUE THREAD

**Issue by AliBahaari** [eternnoir/pyTelegramBotAPI#385] opened 2017-08-08 19:37 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu

3. What version of python are you using? 3.X

Hello, When I run my bot on the computer It works correctly also with Persian characters but when I upload the bot to the server, It has problem with Persian characters. For example I used "print" for showing message.text (the text that the bot gets from the user), but this error triggered :
**UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)**

**Comment by farbodgame** [comment] 2017-08-17 08:14
@AliBahaari Put this line at the top of your python 3 code:

`# coding=utf-8`

I think it should work for you but i notice that you have problem with Persian in your server and you don't have in your computer (Also i'm Persian and i don't have any problem in my server!). So if you did this and again you have the problem please let me see your server locale using this command in your server:
`locale`

**Comment by AliBahaari** [comment] 2017-08-18 16:49
Thank you very much, I'll check that and inform you ...

**Comment by AliBahaari** [comment] 2017-08-18 16:58
@farbodgame Again I had the problem, This is the result of the `locale` command :
```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by farbodgame** [comment] 2017-08-19 04:51
@AliBahaari Yup it looks like that the problem is from `locale` config. 
Use [This](https://perlgeek.de/en/article/set-up-a-clean-utf8-environment) link to config your locale.
In shorthand, you can do this:

1. `sudo locale-gen "en_US.UTF-8"`
2. `sudo dpkg-reconfigure locales` (Make sure to choose **en_US.UTF-8** in this part)

And then you should be fine. Just let me know if it has problem :)

**Comment by AliBahaari** [comment] 2017-08-19 13:37
Thanks I'll check it and inform you ... :+1:

**Comment by AliBahaari** [comment] 2017-08-20 11:56
@farbodgame I did the `locale-gen` and `dpkg-reconfigure`, But still not working :(, When I checked the `locale`, It was still the same as I told you above ...
```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by farbodgame** [comment] 2017-08-20 12:44
@AliBahaari So please enter this command again:

1. sudo dpkg-reconfigure locales ( Make sure to choose **ONLY** _en_US.UTF-8_ )
2. sudo locale-gen "en_US.UTF-8"
3. sudo localectl set-locale LANG="en_US.UTF-8"

And after you entered these commands, restart your server if you can to make sure that every thing is ok. Your locale output should be something like this:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by AliBahaari** [comment] 2017-08-21 17:15
Thank you, Now It's correct ... Again Thanks ...

**Comment by farbodgame** [comment] 2017-08-21 17:25
@AliBahaari Glad i can help.
So if you think the problem is solved please close this issue :)

**Closed** 2017-08-21 21:04 UTC
