### ISSUE TITLE
Read timed out. (read timeout=30) Error

### ISSUE THREAD

**Issue by natijauskas** [eternnoir/pyTelegramBotAPI#474] opened 2018-03-13 22:07 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
six-1.11.0
2. What OS are you using?
Ubuntu 14.04.4 LTS
3. What version of python are you using?
Python 3.4.3

Hello!
I have had this error several times in the past few days and I can not fix it. I use this solution in my code (#251) but I have the same error. Can you help me?
Thanks a lot!

while True:

    try:

        bot.polling(none_stop=True)

    # ConnectionError and ReadTimeout because of possible timout of the requests library

    # TypeError for moviepy errors

    # maybe there are others, therefore Exception

    except Exception as e:

        logger.error(e)

        time.sleep(15)

 File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 537, in <module>
    logger.error(e)

**Comment by marting87** [comment] 2018-03-14 10:19
I have the exact same problem

**Comment by SkymanOne** [comment] 2018-03-20 20:40
Just use webhook...

**Comment by heyyyoyy** [comment] 2018-04-01 12:54
```python 
def polling(self, none_stop=False, interval=0, timeout=20):
```
you should increase the timeout

**Comment by sviat9440** [comment] 2018-04-02 14:28
Same as #473

**Comment by M1LKYWVY** [comment] 2018-04-10 20:29
`while True:
        try:
            bot.polling(none_stop=True)
        except:
            bot.stop_bot()
            time.sleep(10)`
This solution worked for me

**Comment by M1LKYWVY** [comment] 2018-04-10 20:30
while True:
        try:
            bot.polling(none_stop=True)
        except:
            bot.stop_bot()
            time.sleep(10)
This solution worked for me

**Comment by sviat9440** [comment] 2018-04-10 20:34
@M1LKYWVY this implemented by infinity_polling

**Comment by M1LKYWVY** [comment] 2018-04-10 20:37
@sviat9440 I don't know which version pytelegrambotapi u use, but in 3.6.2 I don't have such method.

**Comment by sviat9440** [comment] 2018-04-10 20:38
@M1LKYWVY please download the lasted source code.

**Comment by sviat9440** [comment] 2018-04-10 20:54
@M1LKYWVY #487

**Comment by M1LKYWVY** [comment] 2018-04-10 21:13
@sviat9440 Have downloaded your improvements, but bot still falling down. Nay with your commit.
`ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)),)
`

**Comment by sviat9440** [comment] 2018-04-15 04:10
@M1LKYWVY can't confirm a problem, I have 10 days uptime. Try creating a new project and use this method. If the problem still down, please contact.

**Comment by Sajjadhosn** [comment] 2018-04-17 20:42
@sviat9440 I can confirm too that in 3.6.2, there's no such function as `inifinity_polling` on the bot object. I can see the function, of course, [here](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/__init__.py#L250),  but I'm guessing something is not working as intended since the 3.6.2 on pypi does not have the function.

**Comment by sviat9440** [comment] 2018-04-18 11:12
@Sajjadhosn please download "telebot" folder in root of your bot directory.

**Comment by Sajjadhosn** [comment] 2018-04-18 11:28
@sviat9440 I think I'll wait for 3.6.3. Btw, for other people having this issue, I solved it by passing `timeout=20` to the polling function.

**Comment by sviat9440** [comment] 2018-04-18 11:34
@Sajjadhosn is not correct solution

**Comment by Stihotvor** [comment] 2018-06-13 09:43
Any update?

**Comment by sallyruthstruik** [comment] 2018-07-01 08:56
Got same problem. Infinity_pooling didn't help. I got such error message:
```
2018-07-01 11:54:39,273 (util.py:65 PollingThread) ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', error(101, 'Network is unreachable')),)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 158, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 128, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(101, 'Network is unreachable'))
"
```

**Comment by M1LKYWVY** [comment] 2018-07-02 06:28
@sallyruthstruik Problem can be solved by increasing timeout in polling function. I used `bot.polling(none_stop=True, timeout=123)`. I have more than 15 days uptime with this method.

**Comment by marting87** [comment] 2018-07-02 07:58
The following fixed it for me:

Change Line 53:
```
 result = _get_req_session().request(method, request_url, params=params, files=files,
                                        timeout=(connect_timeout, read_timeout), proxies=proxy)
    logger.debug("The server returned: '{0}'".format(result.text.encode('utf8')))
    return _check_result(method_name, result)['result']
```

To:

```
while True:
        try:
            result = _get_req_session().request(method, request_url, params=params, files=files,
                                            timeout=(connect_timeout, read_timeout), proxies=proxy)

            logger.debug("The server returned: '{0}'".format(result.text.encode('utf8')))
            return _check_result(method_name, result)['result']

        except:
            time.sleep(5);
```
Don't forget to `import time`

**Closed** 2020-01-03 15:05 UTC
